const sidebar_menus = [
  {
    header: "MAIN",
    roles: ["Administrator", "Hub", "Agent"],
  },
  {
    title: "Dashboard",
    icon: "fa-solid fa-gauge",
    link: "/dashboard",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Assessment",
    icon: "fa-solid fa-chalkboard",
    link: "/assessment",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Course Learning Outcome",
    icon: "fa-solid fa-graduation-cap",
    link: "/course-learning-outcome",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    header: "SETUP",
    roles: ["Administrator", "Hub", "Agent"],
  },
  {
    title: "Course",
    icon: "fa-solid fa-book",
    link: "/course",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Rubrik",
    icon: "fa-solid fa-book-open",
    link: "/rubrik",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Student Outcomes (SOs)",
    icon: "fa-solid fa-graduation-cap",
    link: "/student-outcome",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "CDIO Syllabus",
    icon: "fa-solid fa-boxes-stacked",
    link: "/cdio-syllabus",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Assessment Method",
    icon: "fa-solid fa-bars-progress",
    link: "/assessment-method",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Proficiency Level",
    icon: "fa-solid fa-layer-group",
    link: "/proficiency-level",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    header: "PROGRAM STUDI",
    roles: ["Administrator", "Hub", "Agent"],
  },
  {
    title: "Jurusan",
    icon: "fa-solid fa-school",
    link: "/jurusan",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Program Studi",
    icon: "fa-solid fa-school-flag",
    link: "/program-studi",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    header: "UTILITY",
    roles: ["Administrator", "Hub", "Agent"],
  },
  {
    title: "Assessment Type",
    icon: "fa-solid fa-bars-progress",
    link: "/assessment-type",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "Grading Category",
    icon: "fa-solid fa-layer-group",
    link: "/grading-category",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
  {
    title: "User Management",
    icon: "fa-solid fa-users",
    link: "/user-management",
    roles: ["Administrator", "Hub", "Agent"],
    children: false,
  },
];

export default sidebar_menus;
